# -*- coding: utf-8 -*-
"""Lista 2 - PAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133zwM-KnjZSLmfZoslDq_hr0s83Aqbon
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

IMAGE_PATHS = {
    "Image 1": "pessoa.jpg",
    "Image 2": "pucminas.jpg",
    "Image 3": "vaticano.jpg"
}

def process_and_display(image_dict):

    num_images = len(image_dict)

    fig, axes = plt.subplots(num_images, 4, figsize=(20, 5 * num_images))

    if num_images == 1:
        axes = np.array([axes])

    print("Starting processing...")

    for i, (title, path) in enumerate(image_dict.items()):

        img_original = cv2.imread(path)

        if img_original is None:
            print(f"Error: Could not load image '{path}'. Check the path.")
            for j in range(4):
                axes[i, j].text(0.5, 0.5, f"Error loading\n{path}",
                                horizontalalignment='center', verticalalignment='center',
                                color='red')
                axes[i, j].set_title(f"Image: {title}")
                axes[i, j].axis('off')
            continue

        img_gray = cv2.cvtColor(img_original, cv2.COLOR_BGR2GRAY)

        otsu_thresh, img_otsu = cv2.threshold(
            img_gray,
            0,
            255,
            cv2.THRESH_BINARY + cv2.THRESH_OTSU
        )

        img_blur = cv2.GaussianBlur(img_gray, (5, 5), 0)

        canny_thresh_low = otsu_thresh * 0.5
        canny_thresh_high = otsu_thresh

        img_canny_auto = cv2.Canny(img_blur, canny_thresh_low, canny_thresh_high)

        axes[i, 0].imshow(cv2.cvtColor(img_original, cv2.COLOR_BGR2RGB))
        axes[i, 0].set_title(f"{title} (Original)")
        axes[i, 0].axis('off')

        axes[i, 1].imshow(img_gray, cmap='gray')
        axes[i, 1].set_title("Grayscale")
        axes[i, 1].axis('off')

        axes[i, 2].imshow(img_otsu, cmap='gray')
        axes[i, 2].set_title(f"Otsu (Threshold: {otsu_thresh:.0f})")
        axes[i, 2].axis('off')

        axes[i, 3].imshow(img_canny_auto, cmap='gray')
        axes[i, 3].set_title(f"Canny (T_low={canny_thresh_low:.0f}, T_high={canny_thresh_high:.0f})")
        axes[i, 3].axis('off')

    plt.tight_layout()
    plt.suptitle("Comparison: Otsu's Method vs. Canny Edge Detector", fontsize=20, y=1.03)

    output_filename = "comparative_visual_report.png"
    plt.savefig(output_filename)
    print(f"\nResults saved to '{output_filename}'")

    plt.show()

if __name__ == "__main__":
    process_and_display(IMAGE_PATHS)

import cv2 as cv
import numpy as np
import random as rng
from google.colab.patches import cv2_imshow

rng.seed(12345)

def find_and_draw_hull(src_gray, threshold):
    canny_output = cv.Canny(src_gray, threshold, threshold * 2)
    contours, _ = cv.findContours(canny_output, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

    hull_list = []
    for i in range(len(contours)):
        hull = cv.convexHull(contours[i])
        hull_list.append(hull)

    drawing = np.zeros((canny_output.shape[0], canny_output.shape[1], 3), dtype=np.uint8)
    for i in range(len(contours)):
        color = (rng.randint(0,256), rng.randint(0,256), rng.randint(0,256))
        cv.drawContours(drawing, contours, i, color)
        cv.drawContours(drawing, hull_list, i, color)

    return drawing

def resize_image_for_display(image, max_width=400):
    (h, w) = image.shape[:2]
    if w > max_width:
        r = max_width / float(w)
        dim = (max_width, int(h * r))
        resized = cv.resize(image, dim, interpolation=cv.INTER_AREA)
        return resized
    return image

image_path = cv.samples.findFile('pucminas.jpg')

src = cv.imread(image_path)

if src is None:
    print('Could not open or find the image:', image_path)
else:
    src_gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
    src_gray = cv.blur(src_gray, (3,3))

    thresh = 100

    processed_image = find_and_draw_hull(src_gray, thresh)

    src_resized = resize_image_for_display(src)
    processed_resized = resize_image_for_display(processed_image)

    h1, w1 = src_resized.shape[:2]
    h2, w2 = processed_resized.shape[:2]

    if h1 < h2:
        padding = np.zeros((h2 - h1, w1, 3), dtype=np.uint8)
        src_resized = np.vstack([src_resized, padding])
    elif h2 < h1:
        padding = np.zeros((h1 - h2, w2, 3), dtype=np.uint8)
        processed_resized = np.vstack([processed_resized, padding])

    combined_image = np.hstack((src_resized, processed_resized))

    print("Original Image vs. Processed Image (Side-by-Side):")
    cv2_imshow(combined_image)

    output_filename = 'processed_hull_image.png'

    cv.imwrite(output_filename, processed_image)
    cv.imwrite('comparison_image.png', combined_image)

    print(f"\nProcessed image saved to Colab environment (Files panel) as: {output_filename}")